### ISSUE TITLE
AirBnB - Rheostat & Dates issue. [Uncaught TypeError: Cannot read property 'color' of undefined on Slider.js:1113]

### ISSUE THREAD

**Issue by Ishtiaque-Shaad** [airbnb/rheostat#204] opened 2018-12-18 12:28 UTC
I am on a project work where I am going to use Airbnb-Rheostat & Airbnb-dates packages both.
Following the directions both on github or npm pages. 
I have included the most general usage code example, and got this error!

`Uncaught TypeError: Cannot read property 'color' of undefined
at Slider.js:1113`

My included packages version list.

```"react-with-styles": "^3.2.1",
"react-with-styles-interface-aphrodite": "^5.0.1",
"rheostat": "^3.0.2",
"react": "^16.7.0-alpha.2",
"react-dom": "^16.7.0-alpha.2",
"react-dates": "^18.2.2",```

Why this issue occur when I call those two components on the same page? and how can I solve it?
Thanks in Advance for the suggestions.

**Comment by majapw** [comment] 2018-12-18 17:35
Hi @Ishtiaque-Shaad, I'm going to close this issue because it's a duplicate of https://github.com/airbnb/rheostat/issues/179.

You can find a bit more information on a solution in:
https://github.com/airbnb/rheostat/issues/179#issuecomment-403536047

**Closed by majapw** 2018-12-18 17:35 UTC
Labels: duplicate

**Comment by Ishtiaque-Shaad** [comment] 2018-12-19 04:49
Thanks for the info... 👍
